try {
  console.log("try statement");
} catch (e) {
  console.log("catch statement");
}
