try {
  console.log("In try statement right now");
  1+2;
} catch (e) {
  console.log("In catch statement right now");
}
