try {
  console.log("try statement");
  throw new Error("awofjaowifjaowifoaiwjfoiawjf");
  console.log("reached end of try clause");
} catch (e) {
  console.log("catch statement");
}
